#!/usr/bin/env python3
"""
gate_suppression.py — Phase B alert suppression for cmd_716

Determines whether a monitor alert should be suppressed based on open
judgement gates (action_required items awaiting Lord's decision).

Suppression rules (AC B-2):
  - Suppressible: P5 (殿手作業滞留), 見回り-1 (STALL), 見回り-6 (UNCOMMITTED)
  - NEVER suppress: P7 (GHA/system), P8 (interactive prompt), daemon alerts
  - P6: suppressed only when no pending dashboard events (basic mtime check)

Gate runtime files (見回り-6 suppression allowlist):
  Files that accumulate as side effects of normal agent operation and
  should NOT trigger 見回り-6 while a judgement gate is open.
"""
from __future__ import annotations

import os
import re
import subprocess
from datetime import datetime, timezone
from typing import NamedTuple

import yaml

JST = timezone(__import__("datetime").timedelta(hours=9))

# Files generated by normal agent operation — suppress 見回り-6 only when
# ALL uncommitted files match these patterns.
_GATE_RUNTIME_PATTERNS = [
    re.compile(r"^queue/reports/[^/]+\.yaml$"),
    re.compile(r"^queue/inbox/[^/]+\.yaml$"),
    re.compile(r"^queue/tasks/[^/]+\.yaml$"),
    re.compile(r"^queue/suggestions\.yaml$"),
    re.compile(r"^queue/external_inbox\.yaml$"),
    re.compile(r"^queue/alert_state\.yaml$"),
    re.compile(r"^queue/auto_cmd_log\.yaml$"),
    re.compile(r"^queue/snapshots/[^/]+\.yaml$"),
    re.compile(r"^memory/[^/]+\.md$"),
    re.compile(r"^scripts/shc\.sh$"),
    re.compile(r"^dashboard\.yaml$"),
]


class GateStatus(NamedTuple):
    has_open_gate: bool
    gate_ids: list  # list[str]
    cmd_ids: list   # list[str] — cmd IDs extracted from gate tags


def get_gate_status(root: str) -> GateStatus:
    """Read dashboard.yaml action_required and return open gate status."""
    dash_path = os.path.join(root, "dashboard.yaml")
    if not os.path.exists(dash_path):
        return GateStatus(has_open_gate=False, gate_ids=[], cmd_ids=[])
    try:
        with open(dash_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return GateStatus(has_open_gate=False, gate_ids=[], cmd_ids=[])

    action_required = data.get("action_required") or []
    if not isinstance(action_required, list):
        return GateStatus(has_open_gate=False, gate_ids=[], cmd_ids=[])

    gate_ids: list = []
    cmd_ids: list = []
    for item in action_required:
        if not isinstance(item, dict):
            continue
        tag = str(item.get("tag") or "")
        # Only HIGH judgement gates count; INFO items are not suppression triggers
        severity = str(item.get("severity") or "").upper()
        if severity == "INFO":
            continue
        if not re.search(r"\[action-\d+\]", tag):
            continue
        gate_id = item.get("gate_id") or tag
        gate_ids.append(str(gate_id))
        # Extract cmd IDs from tag like "[action-1] [cmd_712-phase-a-manual-verify]"
        for m in re.findall(r"\[(cmd_\d+)[^\]]*\]", tag):
            cmd_ids.append(m)

    return GateStatus(
        has_open_gate=len(gate_ids) > 0,
        gate_ids=gate_ids,
        cmd_ids=cmd_ids,
    )


def is_gate_runtime_file(rel_path: str) -> bool:
    """Return True if rel_path matches a gate-related runtime file pattern."""
    normalized = rel_path.lstrip("./").replace("\\", "/")
    return any(p.match(normalized) for p in _GATE_RUNTIME_PATTERNS)


def all_uncommitted_are_gate_runtime(root: str) -> bool:
    """Return True if every uncommitted file is a gate-related runtime file.

    Used for 見回り-6 suppression: suppress only when the entire dirty
    set is accounted for by normal agent operation, not by source changes.
    """
    try:
        result = subprocess.run(
            ["git", "-C", root, "status", "--porcelain"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False

    if not result.stdout.strip():
        return True  # nothing uncommitted

    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        # porcelain: "XY path" — first 2 chars status, char 3 space, rest is path
        # Do NOT strip the line itself before slicing to preserve column positions
        rel = line[3:].strip()
        if " -> " in rel:
            rel = rel.split(" -> ")[-1]
        if not is_gate_runtime_file(rel):
            return False
    return True


def stall_is_gate_driven(root: str, gate_status: GateStatus) -> bool:
    """Return True if ALL in_progress cmds in dashboard.yaml have open gates.

    見回り-1 suppression: if every stalled cmd is waiting on a Lord decision
    gate, the alert is redundant (the gate itself already notified the Lord).
    """
    if not gate_status.has_open_gate:
        return False
    dash_path = os.path.join(root, "dashboard.yaml")
    if not os.path.exists(dash_path):
        return False
    try:
        with open(dash_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return False

    in_progress = data.get("in_progress") or []
    if not in_progress:
        return False  # nothing to suppress

    for item in in_progress:
        if not isinstance(item, dict):
            continue
        cmd = str(item.get("cmd") or "")
        if not cmd:
            continue
        # Check if this cmd has a corresponding open gate
        if not any(cmd in gate_id for gate_id in gate_status.gate_ids):
            return False  # At least one cmd has no gate → keep alert
    return True


def has_pending_dashboard_events(root: str) -> bool:
    """Return True if any source file is newer than dashboard.md.

    Phase B minimal P6 event check (basic mtime approach).
    Full event ledger implementation deferred to Phase C.

    Event sources checked:
      - queue/tasks/*.yaml  (task state changes)
      - queue/reports/*.yaml  (cmd completions, QC)
      - queue/shogun_to_karo.yaml  (new cmd dispatches)
    """
    dash_path = os.path.join(root, "dashboard.md")
    if not os.path.exists(dash_path):
        return False

    try:
        dash_mtime = os.path.getmtime(dash_path)
    except OSError:
        return False

    import glob
    event_globs = [
        os.path.join(root, "queue/tasks/*.yaml"),
        os.path.join(root, "queue/reports/*.yaml"),
        os.path.join(root, "queue/shogun_to_karo.yaml"),
    ]
    for pattern in event_globs:
        for path in glob.glob(pattern):
            try:
                if os.path.getmtime(path) > dash_mtime:
                    return True
            except OSError:
                continue
    return False


def should_suppress_p5(root: str, gate_status: GateStatus) -> bool:
    """P5 (殿手作業滞留) suppression check.

    Suppress when a gate is open AND all unread shogun inbox messages
    are monitoring reminders (in_progress_monitor_alert / reality_check_alert),
    meaning no genuinely NEW action items exist.
    """
    if not gate_status.has_open_gate:
        return False

    inbox_path = os.path.join(root, "queue/inbox/shogun.yaml")
    if not os.path.exists(inbox_path):
        return False
    try:
        with open(inbox_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return False

    unread = [
        m for m in (data.get("messages") or [])
        if not m.get("read", True)
    ]
    if not unread:
        return False  # nothing unread — P5 should not fire anyway

    # If ANY unread message is a genuine action/decision request, don't suppress
    genuine_types = {"action_required", "decision_required", "cmd_complete"}
    for m in unread:
        if m.get("type") in genuine_types:
            return False  # New real item → keep P5

    # All unread are monitor reminders → suppress
    return True


def should_suppress_stall(root: str, gate_status: GateStatus) -> bool:
    """見回り-1 (dashboard stall) suppression check."""
    return stall_is_gate_driven(root, gate_status)


def should_suppress_uncommitted(root: str, gate_status: GateStatus) -> bool:
    """見回り-6 (git uncommitted) suppression check."""
    if not gate_status.has_open_gate:
        return False
    return all_uncommitted_are_gate_runtime(root)
