#!/usr/bin/env python3
"""
gate_suppression.py — Phase B/C alert suppression + P6 event ledger for cmd_716

Determines whether a monitor alert should be suppressed based on open
judgement gates (action_required items awaiting Lord's decision).

Suppression rules (AC B-2):
  - Suppressible: P5 (殿手作業滞留), 見回り-1 (STALL), 見回り-6 (UNCOMMITTED)
  - NEVER suppress: P7 (GHA/system), P8 (interactive prompt), daemon alerts
  - P6: event ledger driven — fire only when unresolved dashboard events exist

Phase C P6 event ledger:
  Tracks dashboard-relevant events with event_kind/source_id/source_mtime/
  first_seen_at/resolved_at fields. Events auto-resolve when dashboard.md
  becomes newer than the source mtime. Persisted in queue/alert_state.yaml
  under the `dashboard_events` key.

Gate runtime files (見回り-6 suppression allowlist):
  Files that accumulate as side effects of normal agent operation and
  should NOT trigger 見回り-6 while a judgement gate is open.
"""
from __future__ import annotations

import glob
import os
import re
import subprocess
import tempfile
from datetime import datetime, timedelta, timezone
from typing import NamedTuple

import yaml

JST = timezone(timedelta(hours=9))

# Phase C P6 event ledger constants
_ALERT_STATE_REL = "queue/alert_state.yaml"
_DASHBOARD_REL = "dashboard.md"
_LEDGER_RESOLVED_KEEP = 50  # keep last N resolved events for audit

# event_kind classification by source path pattern
_EVENT_KIND_PATTERNS = [
    (re.compile(r"^queue/tasks/[^/]+\.yaml$"), "task_status_change"),
    (re.compile(r"^queue/reports/gunshi_report\.yaml$"), "qc_completed"),
    (re.compile(r"^queue/reports/[^/]+\.yaml$"), "report_appended"),
    (re.compile(r"^queue/shogun_to_karo\.yaml$"), "cmd_dispatched"),
]

# Sources scanned for P6 event detection (relative globs from project root)
_EVENT_SOURCE_GLOBS = [
    "queue/tasks/*.yaml",
    "queue/reports/*.yaml",
    "queue/shogun_to_karo.yaml",
]

# Files generated by normal agent operation — suppress 見回り-6 only when
# ALL uncommitted files match these patterns.
_GATE_RUNTIME_PATTERNS = [
    re.compile(r"^queue/reports/[^/]+\.yaml$"),
    re.compile(r"^queue/inbox/[^/]+\.yaml$"),
    re.compile(r"^queue/tasks/[^/]+\.yaml$"),
    re.compile(r"^queue/suggestions\.yaml$"),
    re.compile(r"^queue/external_inbox\.yaml$"),
    re.compile(r"^queue/alert_state\.yaml$"),
    re.compile(r"^queue/auto_cmd_log\.yaml$"),
    re.compile(r"^queue/snapshots/[^/]+\.yaml$"),
    re.compile(r"^memory/[^/]+\.md$"),
    re.compile(r"^scripts/shc\.sh$"),
    re.compile(r"^dashboard\.yaml$"),
]


class GateStatus(NamedTuple):
    has_open_gate: bool
    gate_ids: list  # list[str]
    cmd_ids: list   # list[str] — cmd IDs extracted from gate tags


def get_gate_status(root: str) -> GateStatus:
    """Read dashboard.yaml action_required and return open gate status."""
    dash_path = os.path.join(root, "dashboard.yaml")
    if not os.path.exists(dash_path):
        return GateStatus(has_open_gate=False, gate_ids=[], cmd_ids=[])
    try:
        with open(dash_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return GateStatus(has_open_gate=False, gate_ids=[], cmd_ids=[])

    action_required = data.get("action_required") or []
    if not isinstance(action_required, list):
        return GateStatus(has_open_gate=False, gate_ids=[], cmd_ids=[])

    gate_ids: list = []
    cmd_ids: list = []
    for item in action_required:
        if not isinstance(item, dict):
            continue
        tag = str(item.get("tag") or "")
        # Only HIGH judgement gates count; INFO items are not suppression triggers
        severity = str(item.get("severity") or "").upper()
        if severity == "INFO":
            continue
        if not re.search(r"\[action-\d+\]", tag):
            continue
        gate_id = item.get("gate_id") or tag
        gate_ids.append(str(gate_id))
        # Extract cmd IDs from tag like "[action-1] [cmd_712-phase-a-manual-verify]"
        for m in re.findall(r"\[(cmd_\d+)[^\]]*\]", tag):
            cmd_ids.append(m)

    return GateStatus(
        has_open_gate=len(gate_ids) > 0,
        gate_ids=gate_ids,
        cmd_ids=cmd_ids,
    )


def is_gate_runtime_file(rel_path: str) -> bool:
    """Return True if rel_path matches a gate-related runtime file pattern."""
    normalized = rel_path.lstrip("./").replace("\\", "/")
    return any(p.match(normalized) for p in _GATE_RUNTIME_PATTERNS)


def all_uncommitted_are_gate_runtime(root: str) -> bool:
    """Return True if every uncommitted file is a gate-related runtime file.

    Used for 見回り-6 suppression: suppress only when the entire dirty
    set is accounted for by normal agent operation, not by source changes.
    """
    try:
        result = subprocess.run(
            ["git", "-C", root, "status", "--porcelain"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return False

    if not result.stdout.strip():
        return True  # nothing uncommitted

    for line in result.stdout.splitlines():
        if not line.strip():
            continue
        # porcelain: "XY path" — first 2 chars status, char 3 space, rest is path
        # Do NOT strip the line itself before slicing to preserve column positions
        rel = line[3:].strip()
        if " -> " in rel:
            rel = rel.split(" -> ")[-1]
        if not is_gate_runtime_file(rel):
            return False
    return True


def stall_is_gate_driven(root: str, gate_status: GateStatus) -> bool:
    """Return True if ALL in_progress cmds in dashboard.yaml have open gates.

    見回り-1 suppression: if every stalled cmd is waiting on a Lord decision
    gate, the alert is redundant (the gate itself already notified the Lord).
    """
    if not gate_status.has_open_gate:
        return False
    dash_path = os.path.join(root, "dashboard.yaml")
    if not os.path.exists(dash_path):
        return False
    try:
        with open(dash_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return False

    in_progress = data.get("in_progress") or []
    if not in_progress:
        return False  # nothing to suppress

    for item in in_progress:
        if not isinstance(item, dict):
            continue
        cmd = str(item.get("cmd") or "")
        if not cmd:
            continue
        # Check if this cmd has a corresponding open gate
        if not any(cmd in gate_id for gate_id in gate_status.gate_ids):
            return False  # At least one cmd has no gate → keep alert
    return True


def has_pending_dashboard_events(root: str) -> bool:
    """Return True if any source file is newer than dashboard.md.

    Phase B minimal P6 event check (basic mtime approach).
    Full event ledger implementation deferred to Phase C.

    Event sources checked:
      - queue/tasks/*.yaml  (task state changes)
      - queue/reports/*.yaml  (cmd completions, QC)
      - queue/shogun_to_karo.yaml  (new cmd dispatches)
    """
    dash_path = os.path.join(root, "dashboard.md")
    if not os.path.exists(dash_path):
        return False

    try:
        dash_mtime = os.path.getmtime(dash_path)
    except OSError:
        return False

    import glob
    event_globs = [
        os.path.join(root, "queue/tasks/*.yaml"),
        os.path.join(root, "queue/reports/*.yaml"),
        os.path.join(root, "queue/shogun_to_karo.yaml"),
    ]
    for pattern in event_globs:
        for path in glob.glob(pattern):
            try:
                if os.path.getmtime(path) > dash_mtime:
                    return True
            except OSError:
                continue
    return False


# ────────────────────────────────────────────────────────────
# Phase C: P6 event ledger
# ────────────────────────────────────────────────────────────


def _iso_jst_now() -> str:
    return datetime.now(JST).isoformat(timespec="seconds")


def _iso_jst_from_epoch(epoch: float) -> str:
    return datetime.fromtimestamp(epoch, tz=JST).isoformat(timespec="seconds")


def _parse_iso(value: str) -> "datetime | None":
    if not value:
        return None
    s = str(value).strip()
    if s.endswith("Z"):
        s = s[:-1] + "+00:00"
    try:
        t = datetime.fromisoformat(s)
        if t.tzinfo is None:
            t = t.replace(tzinfo=JST)
        return t
    except (ValueError, TypeError):
        return None


def _canonical_source_id(root: str, abs_path: str) -> str:
    try:
        rel = os.path.relpath(abs_path, root)
    except ValueError:
        rel = abs_path
    return rel.replace("\\", "/")


def classify_event_kind(rel_source_id: str) -> str:
    """Return the event_kind label for a relative source path."""
    normalized = rel_source_id.lstrip("./").replace("\\", "/")
    for pattern, kind in _EVENT_KIND_PATTERNS:
        if pattern.match(normalized):
            return kind
    return "unknown"


def _alert_state_path(root: str) -> str:
    return os.path.join(root, _ALERT_STATE_REL)


def load_event_ledger(root: str) -> dict:
    """Load full alert_state.yaml. Returns a dict with at least gates/notifications/dashboard_events keys."""
    state_path = _alert_state_path(root)
    data: dict = {}
    if os.path.exists(state_path):
        try:
            with open(state_path, encoding="utf-8") as f:
                loaded = yaml.safe_load(f)
            if isinstance(loaded, dict):
                data = loaded
        except (yaml.YAMLError, OSError):
            data = {}
    if not isinstance(data.get("gates"), dict):
        data["gates"] = data.get("gates") or {}
    if not isinstance(data.get("notifications"), dict):
        data["notifications"] = data.get("notifications") or {}
    if not isinstance(data.get("dashboard_events"), list):
        data["dashboard_events"] = []
    return data


def save_event_ledger(root: str, state: dict) -> bool:
    """Persist alert_state.yaml atomically. Returns True on success."""
    state_path = _alert_state_path(root)
    try:
        os.makedirs(os.path.dirname(state_path), exist_ok=True)
        fd, tmp_path = tempfile.mkstemp(
            prefix=".alert_state.", suffix=".yaml.tmp",
            dir=os.path.dirname(state_path),
        )
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                yaml.safe_dump(state, f, allow_unicode=True, sort_keys=False)
            os.replace(tmp_path, state_path)
        except Exception:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise
        return True
    except (OSError, yaml.YAMLError):
        return False


def _event_key(event: dict) -> tuple:
    return (str(event.get("event_kind") or ""), str(event.get("source_id") or ""))


def _scan_event_sources(root: str) -> list:
    """Scan all P6 event source files. Returns list of (source_id, mtime_epoch, event_kind)."""
    found: list = []
    seen: set = set()
    for pattern in _EVENT_SOURCE_GLOBS:
        for path in glob.glob(os.path.join(root, pattern)):
            try:
                mtime = os.path.getmtime(path)
            except OSError:
                continue
            source_id = _canonical_source_id(root, path)
            if source_id in seen:
                continue
            seen.add(source_id)
            kind = classify_event_kind(source_id)
            found.append((source_id, mtime, kind))
    return found


def _dashboard_md_mtime(root: str) -> "float | None":
    dash_path = os.path.join(root, _DASHBOARD_REL)
    if not os.path.exists(dash_path):
        return None
    try:
        return os.path.getmtime(dash_path)
    except OSError:
        return None


def _source_mtime_epoch(root: str, event: dict) -> "float | None":
    """Return the current epoch mtime of the event's source file, or None if missing."""
    source_id = event.get("source_id")
    if not source_id:
        return None
    path = os.path.join(root, str(source_id))
    if not os.path.exists(path):
        return None
    try:
        return os.path.getmtime(path)
    except OSError:
        return None


def update_event_ledger(root: str) -> dict:
    """Scan event sources and update the ledger; return updated state dict.

    Algorithm:
      1. Load existing state (gates/notifications/dashboard_events).
      2. Resolve previously-unresolved events whose source file is now <=
         dashboard.md mtime (compared in epoch seconds, not ISO strings).
      3. Scan event sources for current mtimes; record any source newer
         than dashboard.md that isn't already tracked as unresolved.
         Re-opens previously-resolved entries if the source changed again.
      4. Prune resolved events beyond the keep limit.
      5. Persist atomically.
    """
    state = load_event_ledger(root)
    ledger: list = list(state.get("dashboard_events") or [])
    dash_mtime = _dashboard_md_mtime(root)
    now_iso = _iso_jst_now()

    # Step 2: resolve existing unresolved events using current source mtimes
    if dash_mtime is not None:
        dash_iso = _iso_jst_from_epoch(dash_mtime)
        for event in ledger:
            if not isinstance(event, dict):
                continue
            if event.get("resolved_at"):
                continue
            src_epoch = _source_mtime_epoch(root, event)
            if src_epoch is None:
                continue
            if src_epoch <= dash_mtime:
                event["resolved_at"] = dash_iso

    by_key: dict = {}
    for event in ledger:
        if isinstance(event, dict):
            by_key[_event_key(event)] = event

    # Step 3: scan sources newer than dashboard.md → add or re-open
    scanned = _scan_event_sources(root)
    for source_id, mtime, kind in scanned:
        if dash_mtime is not None and mtime <= dash_mtime:
            continue  # already reflected
        key = (kind, source_id)
        existing = by_key.get(key)
        source_mtime_iso = _iso_jst_from_epoch(mtime)
        if existing is None:
            new_event = {
                "event_kind": kind,
                "source_id": source_id,
                "source_mtime": source_mtime_iso,
                "first_seen_at": now_iso,
                "resolved_at": None,
            }
            ledger.append(new_event)
            by_key[key] = new_event
        elif existing.get("resolved_at"):
            # Source moved again after a prior resolution → re-open
            existing["source_mtime"] = source_mtime_iso
            existing["first_seen_at"] = now_iso
            existing["resolved_at"] = None
        else:
            # Already unresolved → refresh source_mtime for visibility
            existing["source_mtime"] = source_mtime_iso

    # Step 4: prune
    resolved = [e for e in ledger if isinstance(e, dict) and e.get("resolved_at")]
    unresolved = [e for e in ledger if isinstance(e, dict) and not e.get("resolved_at")]
    resolved.sort(key=lambda e: str(e.get("resolved_at") or ""), reverse=True)
    state["dashboard_events"] = unresolved + resolved[:_LEDGER_RESOLVED_KEEP]

    save_event_ledger(root, state)
    return state


def unresolved_events(state: dict) -> list:
    """Return list of unresolved dashboard events from state dict."""
    events = state.get("dashboard_events") or []
    return [e for e in events if isinstance(e, dict) and not e.get("resolved_at")]


def has_unresolved_dashboard_events(root: str) -> bool:
    """Phase C: True iff the ledger has any unresolved dashboard event.

    Side effect: persists an updated ledger. Safe to call on every P6 check.
    """
    state = update_event_ledger(root)
    return len(unresolved_events(state)) > 0


def event_ledger_detection_rate(root: str, expected_source_ids: list) -> float:
    """PoC helper: fraction of expected source_ids covered by current unresolved ledger.

    For a fixture with N known dashboard-relevant changes, this should return
    >= 0.95 when the ledger correctly tracks them.
    """
    if not expected_source_ids:
        return 1.0
    state = update_event_ledger(root)
    tracked = {str(e.get("source_id") or "") for e in unresolved_events(state)}
    expected = {str(s).replace("\\", "/") for s in expected_source_ids}
    if not expected:
        return 1.0
    hit = len(expected & tracked)
    return hit / len(expected)


# ────────────────────────────────────────────────────────────
# Phase B suppression checks (P5 / 見回り-1 / 見回り-6)
# ────────────────────────────────────────────────────────────


def should_suppress_p5(root: str, gate_status: GateStatus) -> bool:
    """P5 (殿手作業滞留) suppression check.

    Suppress when a gate is open AND all unread shogun inbox messages
    are monitoring reminders (in_progress_monitor_alert / reality_check_alert),
    meaning no genuinely NEW action items exist.
    """
    if not gate_status.has_open_gate:
        return False

    inbox_path = os.path.join(root, "queue/inbox/shogun.yaml")
    if not os.path.exists(inbox_path):
        return False
    try:
        with open(inbox_path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}
    except Exception:
        return False

    unread = [
        m for m in (data.get("messages") or [])
        if not m.get("read", True)
    ]
    if not unread:
        return False  # nothing unread — P5 should not fire anyway

    # If ANY unread message is a genuine action/decision request, don't suppress
    genuine_types = {"action_required", "decision_required", "cmd_complete"}
    for m in unread:
        if m.get("type") in genuine_types:
            return False  # New real item → keep P5

    # All unread are monitor reminders → suppress
    return True


def should_suppress_stall(root: str, gate_status: GateStatus) -> bool:
    """見回り-1 (dashboard stall) suppression check."""
    return stall_is_gate_driven(root, gate_status)


def should_suppress_uncommitted(root: str, gate_status: GateStatus) -> bool:
    """見回り-6 (git uncommitted) suppression check."""
    if not gate_status.has_open_gate:
        return False
    return all_uncommitted_are_gate_runtime(root)
